apiVersion: v1
kind: Pod
metadata:
  name: nginx-mysql-pod
  labels:
    app: myapp
    tier: backend

spec:
  containers:

    # Container 1: Nginx
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80

    # Container 2: MySQL
    - name: mysql-container
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root123"
        - name: MYSQL_DATABASE
          value: "myappdb"
        - name: MYSQL_USER
          value: "myappuser"
        - name: MYSQL_PASSWORD
          value: "mypassword"
      ports:
        - containerPort: 3306

